name: build

on:
  workflow_call:
    inputs:
      project-dir:
        required: true
        type: string
      allow-test-failure:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.23.x', '1.24.x']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go get -v ./...
      working-directory: ${{ inputs.project-dir }}

    - name: Run tests
      run: |
        if [ "${{ inputs.allow-test-failure }}" = "true" ]; then
          make test || echo "Tests failed, but continuing because allow-test-failure is true."
        else
          make test
        fi
      working-directory: ${{ inputs.project-dir }}

    - name: Generate test coverage
      env:
        COV_OUTPUT: ${{ matrix.go-version }}-coverage.out
        COV_HTML_OUTPUT: ${{ matrix.go-version }}-coverage.html
      run: make test-coverage
      working-directory: ${{ inputs.project-dir }}

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.go-version }}-coverage-report
        path: ${{ inputs.project-dir }}/${{ matrix.go-version }}-coverage.html

    - name: Upload raw coverage file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.go-version }}-coverage-raw
        path: ${{ inputs.project-dir }}/${{ matrix.go-version }}-coverage.out

    - name: Cross compile and pack
      run: make production.pack-matrix
      working-directory: ${{ inputs.project-dir }}

    - name: Upload built artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ matrix.go-version }}
        path: ${{ inputs.project-dir }}/dist/*
