name: main

on:
  workflow_dispatch:
    inputs:
      project-dir:
        description: Directory of the Go project to build and test
        required: true
        type: string
        default: 023_build_an_application
      allow-test-failure:
        description: |
          If set to true, the workflow will continue even if tests fail.
          This is useful for development purposes but should be false in production builds.
        required: true
        type: boolean
        default: false

  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project-dir: ${{ github.event.inputs.project-dir || '023_build_an_application' }}
      allow-test-failure: ${{ github.event.inputs['allow-test-failure'] || false }}
